repository:
  name: smart-enterprise-ai-copilot
  description: Smart AI Copilot for enterprise workflows using LangGraph, RAG, and tool execution.
  homepage: https://yourdomain.com
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []  # You can list CI checks like "ci/test"
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions: null