repos:


  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.17.5
#    hooks:
#      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --maxfail=1 --disable-warnings -q
        language: system
        types: [python]